<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>c50ca8cf-42b7-4eb2-9b61-dad5e6455d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bot1-Msg1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bot1-Msg1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56b24010-4478-4ab6-9750-f17c8d63eb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bot1-Msg1</value>
      <webElementGuid>c03c6ad4-fffb-43c3-89d2-ee8f3ea686f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm botTempo</value>
      <webElementGuid>8fc8ef89-7969-49f2-9bc9-f9f93b76375c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Close</value>
      <webElementGuid>d73bb826-b864-4f6a-9fd5-5d3449da66fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bot1-Msg1&quot;)</value>
      <webElementGuid>7461ab95-8295-4412-8b36-63ce50617e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bot1-Msg1']</value>
      <webElementGuid>faa9111f-a9e2-41ed-99d1-690d7953ff0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Msg1']/div/div/button</value>
      <webElementGuid>6b1dbef0-9662-4419-980c-86ed5f5f2699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Webfront'])[1]/following::button[1]</value>
      <webElementGuid>8a52adbd-458b-4b39-89b9-190c609ee167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button</value>
      <webElementGuid>4a289bbf-4433-4d64-bc51-1e1427718908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'bot1-Msg1' and (text() = ' Close' or . = ' Close')]</value>
      <webElementGuid>f3ba61bd-fc28-4f41-95b0-b85ea86294c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
