<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept Cookies</name>
   <tag></tag>
   <elementGuidId>b0796881-024b-4d5d-b600-64f62ac875cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gdpr-cookie-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gdpr-cookie-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Accept Cookies&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10ec11e1-328b-4814-8f38-de3831555b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gdpr-cookie-accept</value>
      <webElementGuid>a9add9c2-d2f9-4bf0-a5ac-6270e8e5aa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>817c6658-72da-498b-bce9-060649dc8faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept Cookies</value>
      <webElementGuid>25b34791-9f4c-42d9-ae25-0cfdeff7d63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gdpr-cookie-accept&quot;)</value>
      <webElementGuid>94735cfb-f7b0-48c7-a5e7-45f290e73c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gdpr-cookie-accept']</value>
      <webElementGuid>6f43931c-9247-4ab0-9b55-b313991dc0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gdpr-cookie-message']/p[2]/button</value>
      <webElementGuid>4330113a-3265-4ec3-a9b6-ca14047d602f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::button[1]</value>
      <webElementGuid>a6543db2-0ee4-40cb-b424-a67934969864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/following::button[1]</value>
      <webElementGuid>e3bfbb0f-d22c-4553-87c2-27c351868f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customise Cookies'])[1]/preceding::button[1]</value>
      <webElementGuid>d1a554ed-73ea-46eb-a365-9b8071b4973e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept Cookies']/parent::*</value>
      <webElementGuid>0596e8e4-749c-4cc4-b0ae-388eb8b8d630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/button</value>
      <webElementGuid>81447322-0116-4216-afea-d5734ad7420e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gdpr-cookie-accept' and @type = 'button' and (text() = 'Accept Cookies' or . = 'Accept Cookies')]</value>
      <webElementGuid>04353792-4433-443a-856c-164b78d6a8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
