<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BOS</name>
   <tag></tag>
   <elementGuidId>aff07d63-4da7-4d5d-90b4-e5de2fe289f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav.panel-tabs > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'BOS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BOS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5944b568-6589-428a-ab92-8f57861c6216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab2</value>
      <webElementGuid>ebd25069-1cd5-4a66-bc53-6f89798eb5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>bffbf382-73c8-409e-9b8b-ca28d75f858c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOS</value>
      <webElementGuid>e1d2cc28-2fa3-4a1a-b087-1906821c0a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;horizontalMenucontainer&quot;]/section[@class=&quot;sptb bg-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;text-justify&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card1&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;tab-menu-heading&quot;]/div[@class=&quot;tabs-menu&quot;]/ul[@class=&quot;nav panel-tabs&quot;]/li[2]/a[1]</value>
      <webElementGuid>da8e61ce-fe28-4625-85d2-ae6724007217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BOS')]</value>
      <webElementGuid>1411c933-319e-470b-9e11-b6584d0db34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders and Regulations'])[1]/following::a[1]</value>
      <webElementGuid>b7d56c96-4e42-41a4-aa28-6810ed7b4ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Page'])[3]/following::a[2]</value>
      <webElementGuid>2cfaa32c-8bc4-438f-b8a7-35c88d04b3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[2]/preceding::a[1]</value>
      <webElementGuid>e4f5dea3-a936-426a-9896-e6691f566a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QIV 2020-21'])[1]/preceding::a[2]</value>
      <webElementGuid>55db9f05-b7a1-45e2-95d2-d48af9b5ab7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOS']/parent::*</value>
      <webElementGuid>083afa5c-ad0c-4415-a43d-b1395c44424e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab2')]</value>
      <webElementGuid>f1eef708-1181-48a6-bd1c-68ea8a3d45d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>3ba1f69f-8d34-4007-9141-5e58f5ee4698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab2' and (text() = 'BOS' or . = 'BOS')]</value>
      <webElementGuid>0edcccca-f270-4ce6-8b0b-a2128f1fdc71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
