<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MBA</name>
   <tag></tag>
   <elementGuidId>53d43d79-34cc-4268-8b30-4410329d41e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'MBA')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;MBA&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9321210c-1f54-469d-8fbb-aede9214a390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>SYLLABUS-FOR-MBA-PROGRAMME32</value>
      <webElementGuid>ee9a5fb2-5871-4776-a745-69f30b05c3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MBA</value>
      <webElementGuid>e64378dc-255d-40b8-b912-a77e3315f36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;horizontalMenucontainer&quot;]/section[@class=&quot;sptb&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-md-12&quot;]/div[@class=&quot;card mb-lg-0&quot;]/div[2]/div[@class=&quot;card-body&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;listunorder1&quot;]/a[1]</value>
      <webElementGuid>055ff9b4-ceb4-4e71-a239-46171ca3ff03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'MBA')])[3]</value>
      <webElementGuid>f05ef7a9-a1d6-4fe9-826f-2bffaa6bbcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.Tech'])[1]/following::a[1]</value>
      <webElementGuid>6f66a39a-a813-4ab6-ace7-ca30a1171376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B Design'])[1]/following::a[2]</value>
      <webElementGuid>177a6b1f-be30-4050-8879-c8c0657b6341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MBA (Agribusiness Management)'])[1]/preceding::a[1]</value>
      <webElementGuid>abc20ad1-9730-426f-85c7-d5db90185d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MCA (2 year programme)'])[1]/preceding::a[2]</value>
      <webElementGuid>a2a761c1-fc24-4168-afc3-8f22b16564aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'SYLLABUS-FOR-MBA-PROGRAMME32')]</value>
      <webElementGuid>aee2e986-b1ac-4ff1-8ce3-8fe648aec039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[4]/a</value>
      <webElementGuid>8faa7e33-ae1a-4e74-9d9c-7892d5776ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'SYLLABUS-FOR-MBA-PROGRAMME32' and (text() = 'MBA' or . = 'MBA')]</value>
      <webElementGuid>e8a1e010-2e88-41ec-87fd-115107c05f8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
