<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notices</name>
   <tag></tag>
   <elementGuidId>29508bad-0f86-4b29-b3fd-b76d60a81d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav.panel-tabs > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Notices')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Notices&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8c062fa-718c-4db3-98fc-159da1d67167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab3</value>
      <webElementGuid>d944369b-a6fd-483d-9f33-9035a4e24915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>0349e324-a4df-4f0a-9ecd-fd7f97d9f44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notices</value>
      <webElementGuid>8c6fb235-445d-4fe0-9973-40bb2a951d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;horizontalMenucontainer&quot;]/section[@class=&quot;sptb bg-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;text-justify&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card1&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;tab-menu-heading&quot;]/div[@class=&quot;tabs-menu&quot;]/ul[@class=&quot;nav panel-tabs&quot;]/li[3]/a[1]</value>
      <webElementGuid>dc6b9e28-8cee-48c3-bebe-934871c86b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Notices')])[3]</value>
      <webElementGuid>f64c71f2-5fba-4f90-a1ed-97eb344a578e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOS'])[1]/following::a[1]</value>
      <webElementGuid>7474d26c-6214-4eef-ab44-c3d5b10a4fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders and Regulations'])[1]/following::a[2]</value>
      <webElementGuid>a94dfbd1-6f67-468f-9444-dbac8421f5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QIV 2020-21'])[1]/preceding::a[1]</value>
      <webElementGuid>670433ce-c183-4e22-8831-c7f19abd7b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anti Ragging Measures'])[1]/preceding::a[2]</value>
      <webElementGuid>124029a1-edaa-4c02-9019-7903494d1be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab3')]</value>
      <webElementGuid>2be61435-a5c0-4fa1-a168-3179fd319a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>52809343-3dee-4d88-b52d-e28125b066df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab3' and (text() = 'Notices' or . = 'Notices')]</value>
      <webElementGuid>917258da-c342-4343-812d-8e73f2633f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
