<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notices_1</name>
   <tag></tag>
   <elementGuidId>e41cb72f-a19a-41b7-8f74-3ebdd1430a3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(8) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky-wrapper']/div/div/nav/ul/li[3]/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Notices&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4965ac51-d015-494b-b5b0-c7bb485b99fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Notices36</value>
      <webElementGuid>70ad03c0-d041-4d1e-b4ad-f9880dcbeeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notices</value>
      <webElementGuid>adbede11-40c4-480c-9c30-69655d59f91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky-wrapper&quot;)/div[@class=&quot;header-style horizontal-main bg-dark-transparent clearfix&quot;]/div[@class=&quot;horizontal-mainwrapper container clearfix&quot;]/nav[@class=&quot;horizontalMenu clearfix d-md-flex&quot;]/ul[@class=&quot;horizontalMenu-list&quot;]/li[3]/ul[@class=&quot;sub-menu&quot;]/li[8]/a[1]</value>
      <webElementGuid>8bc58a80-1f41-42f7-a4a1-697ae778d2a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky-wrapper']/div/div/nav/ul/li[3]/ul/li[8]/a</value>
      <webElementGuid>fbfcef50-f65f-4572-b885-2a188f9f3360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Notices')]</value>
      <webElementGuid>471d7e4a-9af3-4f4f-8140-d6ec5d49b169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board of Studies'])[1]/following::a[1]</value>
      <webElementGuid>f3e34cc8-7c71-471b-821f-0bb53bfaf5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality Index Value (QIV)'])[1]/following::a[2]</value>
      <webElementGuid>a8e9c90b-3ba3-4987-a5d8-442cf53b674c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/preceding::a[1]</value>
      <webElementGuid>d4d981e6-11ab-4985-9b56-5e2d37c4db9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regulations'])[1]/preceding::a[2]</value>
      <webElementGuid>f3239014-2df3-4ab6-889e-512fb0116b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notices']/parent::*</value>
      <webElementGuid>81c0e31a-0bb2-4cc6-af37-9b6fb7c08c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Notices36')]</value>
      <webElementGuid>77d492cd-209c-4538-b459-afa56ce2427c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[8]/a</value>
      <webElementGuid>6c999491-fee6-42e2-9788-fcf39738162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Notices36' and (text() = 'Notices' or . = 'Notices')]</value>
      <webElementGuid>cf887e81-75ca-48d9-bb73-eb7cba50b209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
