<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Orders</name>
   <tag></tag>
   <elementGuidId>8146bc31-795c-4d06-a039-5e9a760b9789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky-wrapper']/div/div/nav/ul/li[3]/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Orders&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>492ed84c-5052-4f09-ba79-b2f183374822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Orders37</value>
      <webElementGuid>e9339c85-2e83-40bd-b133-ec5e2c2fddbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orders</value>
      <webElementGuid>94a17e02-5323-4fef-8a48-2c8e2c5ad7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky-wrapper&quot;)/div[@class=&quot;header-style horizontal-main bg-dark-transparent clearfix&quot;]/div[@class=&quot;horizontal-mainwrapper container clearfix&quot;]/nav[@class=&quot;horizontalMenu clearfix d-md-flex&quot;]/ul[@class=&quot;horizontalMenu-list&quot;]/li[3]/ul[@class=&quot;sub-menu&quot;]/li[9]/a[1]</value>
      <webElementGuid>64a496af-a77c-4d4c-97fa-6a73f707f290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky-wrapper']/div/div/nav/ul/li[3]/ul/li[9]/a</value>
      <webElementGuid>2550cbbf-89d5-43f7-8351-c835845d9004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Orders')]</value>
      <webElementGuid>ba23fc81-c864-4673-95f9-aaed5c24b57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[1]/following::a[1]</value>
      <webElementGuid>2ef533a7-9269-45ae-b9e3-9bc97d53d0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board of Studies'])[1]/following::a[2]</value>
      <webElementGuid>940d303d-288a-45b0-826e-7276b4e61a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regulations'])[1]/preceding::a[1]</value>
      <webElementGuid>f259b48a-599b-4d9e-8115-09789416e437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research'])[1]/preceding::a[2]</value>
      <webElementGuid>809ddb4c-07ff-48c2-a215-25686045fcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orders']/parent::*</value>
      <webElementGuid>d4df0fa5-8461-4c87-9e1f-1beed1f369e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Orders37')]</value>
      <webElementGuid>ffab6ce5-4b9b-414f-98d8-9078733679bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>7635cd25-3980-49be-a055-9a1cf42d7ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Orders37' and (text() = 'Orders' or . = 'Orders')]</value>
      <webElementGuid>eb6f5db0-ad59-42dc-90f9-67e97dc875a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
