<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Faculties</name>
   <tag></tag>
   <elementGuidId>98dd42e2-ae34-41a2-b8c3-3265199f5e8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Faculties&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b5df1386-d7bc-4b8c-96c7-c07a4e15389d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resp-tab-item tabs-lg-collapsed</value>
      <webElementGuid>1f3e2b9b-eda1-4a3a-93cb-ea12a5fb4cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tabs-lg-collapsed_tab_item-2</value>
      <webElementGuid>e1ada052-7c60-41c7-b868-337bacddd5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>67a9b56e-bf81-4e12-b8b9-4754dc5d97e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Faculties</value>
      <webElementGuid>43b3e2cd-d052-4d28-b140-4f14f051d3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wide wow-animation smoothscroll scrollTo desktop landscape rd-navbar-static-linked&quot;]/body[1]/div[@class=&quot;page text-center&quot;]/main[@class=&quot;page-content&quot;]/section[@class=&quot;section-90 section-md-114 section-md-bottom-190&quot;]/div[@class=&quot;shell&quot;]/div[@class=&quot;responsive-tabs responsive-tabs-classic vertical resp-vtabs tabs-lg-collapsed&quot;]/ul[@class=&quot;resp-tabs-list tabs-1 text-center tabs-lg-collapsed&quot;]/li[@class=&quot;resp-tab-item tabs-lg-collapsed&quot;]</value>
      <webElementGuid>a49f69cd-16bc-4f18-973b-b7bc265f8e7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[1]</value>
      <webElementGuid>a8bffc06-42eb-4beb-a3b8-895fa3b9ee9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/following::li[2]</value>
      <webElementGuid>d32bb181-0284-44c1-88b0-995368ce6386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[1]/preceding::li[1]</value>
      <webElementGuid>6fb6397c-7ab6-4755-830b-ab1503825264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Learning'])[1]/preceding::li[2]</value>
      <webElementGuid>75ef3c8f-a36d-4370-ad6e-d1d6fd3433b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Faculties']/parent::*</value>
      <webElementGuid>51dfbdcd-8892-4da9-b93f-1af8324dab3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/section/div/div/ul/li[3]</value>
      <webElementGuid>61844210-2d67-40d1-b22d-7eb1657f7123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Faculties' or . = 'Faculties')]</value>
      <webElementGuid>498c75f2-16bc-401c-b77c-a6b784e3cb54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
