<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Notices</name>
   <tag></tag>
   <elementGuidId>00eb9f14-de37-4700-a903-086f7951ff2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Faculties'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Notices&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ed315e58-ff30-46a1-942d-98eb3e21d31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resp-tab-item tabs-lg-collapsed</value>
      <webElementGuid>92b68999-5088-4553-8bdd-12cc43ee7678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tabs-lg-collapsed_tab_item-3</value>
      <webElementGuid>3d5a2ee8-8aa9-456f-b2c9-6eb3e7cda25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e72b2ec5-46d2-4870-bc4f-a6eacc364d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notices</value>
      <webElementGuid>4d83f42a-9e88-4fcd-9d3e-8c0a51ebaef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wide wow-animation smoothscroll scrollTo desktop landscape rd-navbar-static-linked&quot;]/body[1]/div[@class=&quot;page text-center&quot;]/main[@class=&quot;page-content&quot;]/section[@class=&quot;section-90 section-md-114 section-md-bottom-190&quot;]/div[@class=&quot;shell&quot;]/div[@class=&quot;responsive-tabs responsive-tabs-classic vertical resp-vtabs tabs-lg-collapsed&quot;]/ul[@class=&quot;resp-tabs-list tabs-1 text-center tabs-lg-collapsed&quot;]/li[@class=&quot;resp-tab-item tabs-lg-collapsed&quot;]</value>
      <webElementGuid>8398084e-56a3-401f-870c-ec1845b741f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faculties'])[1]/following::li[1]</value>
      <webElementGuid>84867493-3bc5-4c23-a77a-8727755d5cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[2]</value>
      <webElementGuid>8959788a-3e06-44b7-9526-e6140a0a6317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Learning'])[1]/preceding::li[1]</value>
      <webElementGuid>315fd0ec-fc72-40d8-815b-cbb8ba347594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[3]/preceding::li[2]</value>
      <webElementGuid>66584834-dae5-44ab-ba4e-b772f870f037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notices']/parent::*</value>
      <webElementGuid>17cff11d-3741-4ea7-97ee-c1ae99cf24dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/ul/li[4]</value>
      <webElementGuid>63a85165-da92-4964-ab0a-5d6e8856ea3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Notices' or . = 'Notices')]</value>
      <webElementGuid>6017a400-7a49-4e06-b772-452c4c38bbb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
