<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Faculties</name>
   <tag></tag>
   <elementGuidId>a1138dd8-1b63-43fa-ab5b-b17553539a5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Faculties&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>19baa6de-aabf-45a8-a8ba-aa1c0a789e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resp-tab-item tabs-lg-collapsed</value>
      <webElementGuid>93e5648d-f31a-47ce-9a59-60950ff1337b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tabs-lg-collapsed_tab_item-2</value>
      <webElementGuid>da06e1e8-7b6c-4eb1-aa1e-fffd852e22e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>989ea635-b27a-452e-865f-01f096b68684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Faculties</value>
      <webElementGuid>ba99919b-17af-4039-ba9e-764850f36810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wide wow-animation smoothscroll scrollTo desktop landscape rd-navbar-static-linked&quot;]/body[1]/div[@class=&quot;page text-center&quot;]/main[@class=&quot;page-content&quot;]/section[@class=&quot;section-90 section-md-114 section-md-bottom-190&quot;]/div[@class=&quot;shell&quot;]/div[@class=&quot;responsive-tabs responsive-tabs-classic vertical resp-vtabs tabs-lg-collapsed&quot;]/ul[@class=&quot;resp-tabs-list tabs-1 text-center tabs-lg-collapsed&quot;]/li[@class=&quot;resp-tab-item tabs-lg-collapsed&quot;]</value>
      <webElementGuid>36339b47-8fda-457d-ace6-c7f16734a0d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[1]</value>
      <webElementGuid>a4716f62-2a95-44fd-ad97-c7d61a5b0fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/following::li[2]</value>
      <webElementGuid>47702e89-f127-4397-b271-e9235bc88988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[1]/preceding::li[1]</value>
      <webElementGuid>bbeb2a39-105f-4c4c-aa69-f6e01d9c9931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Learning'])[1]/preceding::li[2]</value>
      <webElementGuid>e179c8d1-1f50-4131-9190-b294e6620f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Faculties']/parent::*</value>
      <webElementGuid>dc17b45e-5bcf-4355-93e0-6161280bd126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/section/div/div/ul/li[3]</value>
      <webElementGuid>d817e2b5-ff50-422b-ba5e-9913e727f155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Faculties' or . = 'Faculties')]</value>
      <webElementGuid>91c37c5f-1755-41f9-9399-1fa746dec610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
