<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Notices</name>
   <tag></tag>
   <elementGuidId>7c100e98-6834-473d-abff-acc2d3a83719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Faculties'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Notices&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>afd7bbd4-aaeb-4fb4-98a2-bf6a10ae6943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resp-tab-item tabs-lg-collapsed</value>
      <webElementGuid>e9e0dccf-e1e7-4869-bd61-aa8521c1001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tabs-lg-collapsed_tab_item-3</value>
      <webElementGuid>da682bea-7e9a-4eff-84bd-1c0c0377aace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ac669cff-63da-4483-956f-f45e43802ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notices</value>
      <webElementGuid>449a9150-000f-4a3c-953a-c2f8fe96609d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wide wow-animation smoothscroll scrollTo desktop landscape rd-navbar-static-linked&quot;]/body[1]/div[@class=&quot;page text-center&quot;]/main[@class=&quot;page-content&quot;]/section[@class=&quot;section-90 section-md-114 section-md-bottom-190&quot;]/div[@class=&quot;shell&quot;]/div[@class=&quot;responsive-tabs responsive-tabs-classic vertical resp-vtabs tabs-lg-collapsed&quot;]/ul[@class=&quot;resp-tabs-list tabs-1 text-center tabs-lg-collapsed&quot;]/li[@class=&quot;resp-tab-item tabs-lg-collapsed&quot;]</value>
      <webElementGuid>ee5371e7-a0f4-402e-a76b-99a4b600b719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faculties'])[1]/following::li[1]</value>
      <webElementGuid>0e9a6e9a-0232-4fd3-8a1c-cfd46dd233de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[2]</value>
      <webElementGuid>281caa39-7895-4494-a77c-04dc7687b946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Learning'])[1]/preceding::li[1]</value>
      <webElementGuid>5587cfe1-3599-46c2-a4f4-0c6ac6f93999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[3]/preceding::li[2]</value>
      <webElementGuid>d0a50647-3039-4a97-8fa7-f7782801f4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notices']/parent::*</value>
      <webElementGuid>1bed772d-28fe-4b12-8b4a-2c65bdca7fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/ul/li[4]</value>
      <webElementGuid>82506ca1-893f-4fa9-a9d2-fc4f12afeafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Notices' or . = 'Notices')]</value>
      <webElementGuid>79d3cd3a-8bea-4aa9-bb35-9833f4625005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
