<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Faculties</name>
   <tag></tag>
   <elementGuidId>ce7ab10c-97b1-423d-9523-4950a996195e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Faculties&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>284e53cd-008a-4afa-aff4-776f0000e3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resp-tab-item tabs-lg-collapsed</value>
      <webElementGuid>71d374cf-c43a-40c2-b311-8c328e505d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tabs-lg-collapsed_tab_item-2</value>
      <webElementGuid>8e14af79-d146-496d-bd1a-b6ae81f867ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e32875c7-d88d-47f5-99d2-22fde980beb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Faculties</value>
      <webElementGuid>4d22c2a4-f16c-4419-b567-11c18e6dcd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wide wow-animation smoothscroll scrollTo desktop landscape rd-navbar-static-linked&quot;]/body[1]/div[@class=&quot;page text-center&quot;]/main[@class=&quot;page-content&quot;]/section[@class=&quot;section-90 section-md-114 section-md-bottom-190&quot;]/div[@class=&quot;shell&quot;]/div[@class=&quot;responsive-tabs responsive-tabs-classic vertical resp-vtabs tabs-lg-collapsed&quot;]/ul[@class=&quot;resp-tabs-list tabs-1 text-center tabs-lg-collapsed&quot;]/li[@class=&quot;resp-tab-item tabs-lg-collapsed&quot;]</value>
      <webElementGuid>ad110abb-4a42-44c8-950e-09df4471aac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Structure'])[1]/following::li[1]</value>
      <webElementGuid>7b4ba650-db49-4ab6-8ca0-cda31d806116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/following::li[2]</value>
      <webElementGuid>f5e34889-12e9-4b07-b686-1f10c88a2c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[1]/preceding::li[1]</value>
      <webElementGuid>5ffcce0a-d7f8-442c-bbfc-2ff1d048e6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Learning'])[1]/preceding::li[2]</value>
      <webElementGuid>0edcb3b9-a986-4fcb-8b3f-a64b4747ff1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Faculties']/parent::*</value>
      <webElementGuid>0242ae8c-074b-4f0d-8abc-e72b81e76ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/section/div/div/ul/li[3]</value>
      <webElementGuid>6942407f-c43e-417a-b61a-9ea4b2eb64e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Faculties' or . = 'Faculties')]</value>
      <webElementGuid>bc333e53-e42f-4021-b742-c75a21c0e43f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
