<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Grievance</name>
   <tag></tag>
   <elementGuidId>5a976c5f-18dd-4fd7-b2de-76213aadf233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//section[@id='division']/div/ul/li/a)[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Grievance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>703a06a3-0b81-4b5d-914f-050cd9d49410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkstyle</value>
      <webElementGuid>c4dc29c7-294c-454d-a2ca-f35a356c706c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://btu.ac.in/BTU/GSYS/app/login.php</value>
      <webElementGuid>88f3353e-2f91-4883-b822-76b60fa77421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grievance </value>
      <webElementGuid>ad4081be-a36d-4b4f-85c8-3e7d2799e509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-homepage-courses&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;block-dark-background&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-4 width20pers&quot;]/section[@id=&quot;division&quot;]/div[@class=&quot;section-content&quot;]/ul[@class=&quot;list-links&quot;]/li[1]/a[@class=&quot;linkstyle&quot;]</value>
      <webElementGuid>116fa6e2-bbdc-46c0-9e52-9fb95879b09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//section[@id='division']/div/ul/li/a)[17]</value>
      <webElementGuid>783f781f-8d8e-494a-bc18-eea32a96a188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grievance')]</value>
      <webElementGuid>4707d9ea-5ed9-4292-9f47-dff38234cfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Support'])[1]/following::a[1]</value>
      <webElementGuid>0a461176-f266-4f90-8ba8-f7d3d0b641cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[2]/following::a[1]</value>
      <webElementGuid>f4d0b1fc-b968-47ff-be26-83192dc2fa3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Attendance System'])[1]/preceding::a[1]</value>
      <webElementGuid>b959eb69-a094-4d4b-a9d8-4b3f1f580392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect'])[1]/preceding::a[3]</value>
      <webElementGuid>74ce9a8a-2dee-40ed-82c4-b5582079a838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grievance']/parent::*</value>
      <webElementGuid>8e38e943-1406-413a-9d5f-52290b0d8ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://btu.ac.in/BTU/GSYS/app/login.php')]</value>
      <webElementGuid>385559bf-8854-4f38-8dcf-1c73d6b7427c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/section/div/ul/li/a</value>
      <webElementGuid>714f5501-c6ec-4f52-a2a5-b41b9822c5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://btu.ac.in/BTU/GSYS/app/login.php' and (text() = 'Grievance ' or . = 'Grievance ')]</value>
      <webElementGuid>bc096238-0e2a-4ef2-b3a0-92d5a7ef0517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
