<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Training  Placement</name>
   <tag></tag>
   <elementGuidId>35edb158-024a-4b5f-a111-6c6047fd26ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//section[@id='division']/div/ul/li[3]/a)[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Training &amp; Placement&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57f094c1-f045-486f-a6c3-1fe218924314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkstyle</value>
      <webElementGuid>4e273653-c6a1-40a9-b214-144672b037c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c7a76684-2ec5-44d7-a612-314a27fca002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training &amp; Placement</value>
      <webElementGuid>fa79c9e9-6adc-476f-b20c-3b5f1addaa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-homepage-courses&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;block-dark-background&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-4 width20pers&quot;]/section[@id=&quot;division&quot;]/div[@class=&quot;section-content&quot;]/ul[@class=&quot;list-links&quot;]/li[3]/a[@class=&quot;linkstyle&quot;]</value>
      <webElementGuid>dc2f9c6d-ef5d-4ce4-a542-0b85b687a166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//section[@id='division']/div/ul/li[3]/a)[5]</value>
      <webElementGuid>b44670d5-55b9-4d35-8d11-a643f908c995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Training &amp; Placement')]</value>
      <webElementGuid>6e84f06b-de09-403c-9142-47df52d47477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Attendance System'])[1]/following::a[1]</value>
      <webElementGuid>d658b0ce-9350-4f14-b4be-d64dba29618b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grievance'])[1]/following::a[2]</value>
      <webElementGuid>f3a37443-915d-4f43-8ba4-e3c401fa1437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect'])[1]/preceding::a[1]</value>
      <webElementGuid>d2f23054-7d37-4f98-8baf-09ede94d2dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::a[1]</value>
      <webElementGuid>a89f3ae2-525b-452d-8691-67028506c8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Training &amp; Placement']/parent::*</value>
      <webElementGuid>a47b405b-6cf7-4ac2-95b7-0fecc0090308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>2d830ee6-0c26-4490-a3da-4f6ed0c04020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/section/div/ul/li[3]/a</value>
      <webElementGuid>ddf3925a-f2d9-44ff-9a74-d5a0774ff24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Training &amp; Placement' or . = 'Training &amp; Placement')]</value>
      <webElementGuid>1ce290c4-612d-4ebc-8951-5dec38e40b33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
