<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_B.Design</name>
   <tag></tag>
   <elementGuidId>822eeb9f-0883-42b5-99d6-14772cf069c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'B.Design')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;B.Design&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25dd7020-d979-4258-8238-fdef9f9ac363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>BDesign-Time-Table82</value>
      <webElementGuid>48825b05-6b76-43fb-8c4c-240530188676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>B.Design</value>
      <webElementGuid>51b1a641-1411-4cca-8d3b-1259d6f213ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;horizontalMenucontainer&quot;]/section[@class=&quot;sptb&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-md-12&quot;]/div[@class=&quot;card mb-lg-0&quot;]/div[2]/div[@class=&quot;card-body&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;listunorder1&quot;]/a[1]</value>
      <webElementGuid>9756d9b7-2d97-4d1f-9ced-1d6ea1f501e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'B.Design')]</value>
      <webElementGuid>aef06f57-0223-4d3b-8f8f-3dbbc6c38b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B.Tech'])[1]/following::a[1]</value>
      <webElementGuid>cee1636f-be1a-4e71-a903-7872ed83d888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Links'])[1]/following::a[2]</value>
      <webElementGuid>cca0c9e0-4021-4a86-ad6e-e2bc368d3c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B.Arch'])[1]/preceding::a[1]</value>
      <webElementGuid>00c0e506-45da-4f41-b1df-efe42ad498c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.Tech.'])[1]/preceding::a[2]</value>
      <webElementGuid>781ba0e6-a07d-4828-860f-83964b64eec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='B.Design']/parent::*</value>
      <webElementGuid>defe0189-1836-4537-ac80-1ddd763d3f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'BDesign-Time-Table82')]</value>
      <webElementGuid>c4573a48-2f24-4782-8ed1-d3c97fff8a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>14fbc053-e8b3-4971-97d0-850b6e9b8265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'BDesign-Time-Table82' and (text() = 'B.Design' or . = 'B.Design')]</value>
      <webElementGuid>c3772254-1edd-4397-acf7-8a1976952364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
