<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_University_media</name>
   <tag></tag>
   <elementGuidId>7b09053d-f7d1-42f0-a5e9-a90986197983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.media</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/div[3]/div/div/div[2]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;University&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b39da63a-6472-4fee-be43-50ae094825b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media</value>
      <webElementGuid>3d271059-2b03-4e48-9fc8-e167545c7a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;landing-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 col-sm-6 col-6&quot;]/div[@class=&quot;box b1&quot;]/a[1]/div[@class=&quot;media&quot;]</value>
      <webElementGuid>2752ca6e-41d6-4b60-b117-a0be3e1d7432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/div/div[2]/div/a/div</value>
      <webElementGuid>289dae23-9bbd-4e05-a468-af6f48df7e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>acf86795-c1bd-4390-b267-f7e569fb086f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
