<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Artificial Intelligence and Data Science</name>
   <tag></tag>
   <elementGuidId>ef602094-c411-43ff-afdc-80dee99e84c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > ul.list-unstyled.child-navigation1 > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='top']/div/nav/ul/li[5]/ul/li[3]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Artificial Intelligence and Data Science&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e77b1bb9-7d6b-405e-8990-a0f9514a3790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://cet-gov.ac.in/web/department/ece?ref=header</value>
      <webElementGuid>68caa03f-868c-468b-a4c9-6bcee6fd27b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>01285cc0-1834-43ce-8ea3-50ea110b42ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Artificial Intelligence and Data Science</value>
      <webElementGuid>f8924df0-48f8-4dd4-8c52-d1f0ddb6d03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;collapse navbar-collapse bs-navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[5]/ul[@class=&quot;list-unstyled child-navigation&quot;]/li[3]/ul[@class=&quot;list-unstyled child-navigation1&quot;]/li[1]/a[1]</value>
      <webElementGuid>479d45ea-a5a7-4932-8357-7992353ee652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='top']/div/nav/ul/li[5]/ul/li[3]/ul/li/a</value>
      <webElementGuid>858bdf1c-ed15-4071-b036-4eb8af33be50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Artificial Intelligence and Data Science')]</value>
      <webElementGuid>74e500f5-9b59-4de1-989b-e8249d82282c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MBA'])[1]/following::a[2]</value>
      <webElementGuid>d373b266-d8df-4a00-9b75-9eae4ee752ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MBA(AGRI BUSINESS MANAGEMENT/ ENTREPRENEUR SHIP)'])[1]/following::a[3]</value>
      <webElementGuid>6cee53af-2bbd-4202-ad2c-7c2a9ed2b386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ceramic Engineering &amp; Technology'])[1]/preceding::a[1]</value>
      <webElementGuid>b2f6440f-e9ea-4194-bd26-2906e84569a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Civil Engineering'])[1]/preceding::a[2]</value>
      <webElementGuid>5aa4726b-cb0b-4c49-8c4f-b3834ac9e587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Artificial Intelligence and Data Science']/parent::*</value>
      <webElementGuid>f54fc4f8-c716-4b27-83e9-079227378b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://cet-gov.ac.in/web/department/ece?ref=header']</value>
      <webElementGuid>9f90e572-2745-4ac1-a156-7c1390f47632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[3]/ul/li/a</value>
      <webElementGuid>99611380-892f-4641-893b-b7c6467541fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://cet-gov.ac.in/web/department/ece?ref=header' and (text() = 'Artificial Intelligence and Data Science' or . = 'Artificial Intelligence and Data Science')]</value>
      <webElementGuid>b96dba69-deb9-4ba6-ae69-bf797fa5c70c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
