<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MBA</name>
   <tag></tag>
   <elementGuidId>fa9eb945-7e79-4bc0-892e-e58012b72c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > ul.list-unstyled.child-navigation1 > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='top']/div/nav/ul/li[5]/ul/li[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;MBA&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a776790b-1883-4e05-bec6-71f722e872fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://cet-gov.ac.in/web/department/mba?ref=header</value>
      <webElementGuid>47981ede-8647-4262-a30f-08adbb62e7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5349b901-cf05-45af-b80e-e24ea1b290cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MBA</value>
      <webElementGuid>1590544d-8fdb-4d04-acd2-10f5b3d487b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;collapse navbar-collapse bs-navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[5]/ul[@class=&quot;list-unstyled child-navigation&quot;]/li[2]/ul[@class=&quot;list-unstyled child-navigation1&quot;]/li[2]/a[1]</value>
      <webElementGuid>4ba4a6f3-51f3-4bd5-b4f8-fd2f8fc053ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='top']/div/nav/ul/li[5]/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>da13e926-ff23-470c-b1ec-bf13c962d201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'MBA')])[2]</value>
      <webElementGuid>634ed6e3-d199-40fe-ab0f-49318172a564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MBA(AGRI BUSINESS MANAGEMENT/ ENTREPRENEUR SHIP)'])[1]/following::a[1]</value>
      <webElementGuid>5f783535-3f57-41c9-8e5c-5d4cb5441602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MATERIAL SCIENCE AND ENGINEERING'])[1]/following::a[3]</value>
      <webElementGuid>1a1f14aa-b9f9-4224-8827-2af7fb7a2431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artificial Intelligence and Data Science'])[1]/preceding::a[2]</value>
      <webElementGuid>94a456a9-0c80-45ba-aa6a-25f79688a604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ceramic Engineering &amp; Technology'])[1]/preceding::a[3]</value>
      <webElementGuid>02a169fe-1367-4e3e-8c97-0cc0194509a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MBA']/parent::*</value>
      <webElementGuid>310ccaa2-a1ba-4cc8-98d7-afe957ec203f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://cet-gov.ac.in/web/department/mba?ref=header'])[2]</value>
      <webElementGuid>0e907f55-6f08-461a-aff2-41731c806918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>5c510d6f-fdbf-4aab-8e8d-afd6292cf586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://cet-gov.ac.in/web/department/mba?ref=header' and (text() = 'MBA' or . = 'MBA')]</value>
      <webElementGuid>d06d8e64-806a-4cf1-b1f7-9c00a763dc11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
